import Link from 'next/link'
import React from 'react'

function Agreement() {
    return (
        <div className=' dark:text-black'>
            <div className=' text-center py-2 font-semibold text-xl'>
                TERMS OF SERVICE FOR LISTING SERVICES
            </div>


            <ol type='1' className=' space-y-4'>
                <li>
                    <p>
                        This document serves as an electronic record under the amended Information Technology Act, 2000, and the associated rules and regulations. It is generated by a computer system and does not necessitate any physical or digital signatures. This electronic record is being presented in compliance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, mandating the publication of terms for accessing or using the services provided by Webzotica Business Famous Software Private Limited through <a href='https://www.famousbusiness.in' target='_blank' >www.famousbusiness.in</a> Portals. The publication of this document aligns with the requirements outlined in Section 65B(2) of the Indian Evidence Act, 1872.
                    </p>
                </li>

                <li>
                    <p>
                        This Terms of Service delineates the contractual relationship between Vendors (referred to as &quot;Vendor&quot; or &quot;Service Provider,&quot; &quot;You,&quot; or &quot;Your&quot;) and Webzotica Business Famous Software Private Limited (referred to as Famousbusiness.in). It governs the services offered by Webzotica Business Famous Software Private Limited through its website (<a href='https://www.famousbusiness.in'>www.famousbusiness.in</a>), APP, or any other medium collectively referred to as &quot;Portals.&quot; Webzotica Business Famous Software Private Limited provides its services exclusively based on the terms and any subsequent amendments outlined in this Terms of Service. Webzotica Business Famous Software Private Limited&apos;s commitment is to dispatch the Terms of Service to you via your registered email ID, and it is also accessible on Webzotica Business Famous Software Private Limited&apos;s website at https://famousbusiness.in/about/Terms-Condition/seller.
                    </p>
                </li>
                <li>
                    <strong>1)	INTRODUCTION:</strong>
                    <p>
                        The Services (as defined hereinafter) provided by Webzotica Business Famous Software Private Limited through (<a href='https://www.famousbusiness.in' target='_blank'>www.famousbusiness.in</a>) are governed by this agreement. Webzotica Business Famous Software Private Limited is a company incorporated under the Companies Act, 1956, with its registered office located at Building 545 Sector-58 Transport Nagar Ballabgarh Faridabad-121004-Haryana. Famous Business engages in the business of furnishing information about Vendors (as defined hereinafter) offering various products and services (&quot;Information&quot;) in selected towns and cities in India (&quot;Service&quot;) to end users. Operating as both a B2B and B2C Marketplace, Famous Business primarily provides directory services to its Callers/Users based on their requirements and searches made on www.famousbusiness.in&apos;s portals, as applicable to the vendors.
                    </p>
                </li>
                <li>
                    <p>
                        The www.famousbusiness.in search service is accessible to users through multiple platforms, including the Internet, mobile internet, and telephone (voice, text, and SMS). Webzotica Business Famous Software Private Limited serves as a medium connecting the general public with vendors&apos; goods and services listed on www.famousbusiness.in. However, it does not guarantee any business to these Vendors. Vendor details provided by them are specified in the listings available at <a href='https://www.famousbusiness.in'>www.famousbusiness.in</a>&apos;s portals. The primary aim of Webzotica Business Famous Software Private Limited is to offer a swift guide for up-to-date information in a user-friendly manner and through a medium that the end user finds comfortable.
                    </p>
                </li>
                <li>
                    <p>
                        The end users, hereinafter referred to as Callers/Users, of the Service are individuals seeking to purchase goods or avail services and are inquiring about the Vendors of such goods and services. These Terms of Service (defined below) and the invoice mentioned in Clause 13 collectively constitute the entire understanding/contract between Webzotica Business Famous Software Private Limited and the Vendors. In addition to its flagship business www.famousbusiness.in, the holding company Webzotica Business Famous Software Private Limited operates <a href='https://www.famousbusiness.in' target='_blank'>www.famousbusiness.in</a>.
                    </p>
                </li>

                <li>
                    <strong>2) ANALYSIS:</strong>
                </li>
                <li>
                    (a) <strong>&quot;Contract&quot;</strong> refers to this Terms of Service along with all Schedules and Annexures (if any).
                </li>
                <li>
                    (b) References to a party herein shall encompass such party&apos;s successors, permitted assigns, and any persons deriving title under it.
                </li>
                <li>
                    (c) The descriptive headings of Clauses are inserted solely for the convenience of reference and are not intended as complete or accurate descriptions of the content of such Clauses
                </li>
                <li>
                    (d) The use of words in the singular or plural, or with a particular gender, shall not limit the scope or exclude the application of any provision of this Contract to such person or persons unless the context otherwise permits.
                </li>
                <li>
                    (e) Any grammatical form of a defined term herein shall have the same meaning as that of such term, and the words &quot;including&quot; and &quot;includes&quot; herein shall always mean &quot;including, without limitation&quot; and &quot;includes, without limitation,&quot; respectively
                </li>



                {/* business Listing */}

                <li>
                    <strong>BUSINESS LISTINGS:</strong>
                    <p>
                        Webzotica Business Famous Software Private Limited, Famousbusiness.in Portal in alignment with the Digital India campaign&apos;s mission, aims to empower over 10 million Micro, Small & Medium Enterprises (MSMEs) by facilitating their digital transformation. Our commitment involves providing a Free Digital Business Page, supporting the ethos of &quot;Power To Empower.&quot; Leveraging technology and innovation, we strive to assist Indian MSMEs in embracing digitization, thereby enabling them to compete and succeed in the digital era.
                    </p>
                </li>
                <li>
                    As part of our comprehensive services, we offer Free Bulk Data Uploading for India&apos;s Business Listing Digital Business Page, utilizing available resources and business data for the Digital India Campaign. We specialize in creating business pages tailored to specific cities and pin codes, positioning ourselves as the sole marketplace providing an all-encompassing solution for MSMEs. Our offerings extend beyond basic listings, incorporating tools such as GST Invoice Maker, Live Leads Bucket, Tender Bucket, Ads Posting, and Free Job Posting to propel businesses to the next tech-enabled level.
                </li>
                <li>
                    We understand that business dynamics may change, and to respect the autonomy of business owners, we provide a seamless process for opting out. Should a business owner choose to discontinue their presence on our portal, they can effortlessly apply for the removal of their business page or unsubscribe from our services. In such cases, we promptly take action to remove the business page from our platform. It is imperative to note that, in doing so, the business owner agrees not to pursue any legal action or issue notices against Webzotica Business Famous Software Private Limited related to the creation of their business page.
                </li>


                {/* Premium */}

                <li>
                    <strong>PREMIUM LISTING:</strong>
                    <p>
                        The Vendor acknowledges that the <b>PREMIUM PLAN</b> constitutes position-based services, which may be fixed or rotational in nature, as reasonably determined by Famousbusiness.in, based on availability in selected categories and pin codes. Under rotational search, for specific area searches, vendor listings will appear in positions chosen by them. For all area searches, listings will be displayed rotationally based on amounts paid for that category.
                    </p>
                </li>
                <li>
                    The Vendor agrees to enlist itself under the Listing, with package values subject to variation based on city, town, medium, category, and other parameters identified by Famousbusiness.in. If Vendors wish to change/add any categories/pin codes, it can be done at no additional cost, depending on availability and Famousbusiness.in&apos;s discretion. However, in the case of removal/cancellation/deletion of any categories/pin codes in the existing listing, Vendors shall not claim a reduction in cost or a refund based on such removal/cancellation/deletion.
                </li>
                <li>
                    Famousbusiness.in reserves the right to modify Listing Service options by adding new listings, deleting existing listings, or altering categories, keywords, or pin codes. If the applied-for listing is no longer available, Famousbusiness.in will make efforts to allocate a similar listing to the Vendor. The final decision-making power regarding Listings rests with Famousbusiness.in, and such decisions are deemed final and binding on the Vendor.
                </li>


                {/* tags */}
                {/* tags */}
                <li>
                    <strong>Verified Icon:</strong>
                    The <b>&quot;Famous Business Verified Icon&quot;</b> serves as confirmation that we have diligently verified the identity and information of vendors/services, including names, addresses, contact details, and business names. This verification is based on the documents or information provided by the vendors/service providers. The awarding of the &quot;Famous Business Trusted Tag&quot; is not solely dependent on document verification; it may also take into account user reviews, ratings, or other pertinent criteria as determined by Famous Business.

                </li>
                <li>
                    <strong>Trending Tag:</strong>
                    The &quot;Famous Business Trending Tag&quot; signifies that the identity and details of vendors/services, such as names, addresses, contact information, and business names, have been verified to the best of our ability. This verification process relies on the documents or information submitted by the vendors/service providers. The assignment of the &quot;Famous Business Trusted Tag&quot; is not exclusively based on document verification; it may also consider user reviews, ratings, or other relevant criteria deemed important by Famous Business.

                </li>
                <li>
                    <strong>Industry Leader:</strong>
                    The &quot;Famous Business Industry Leader&quot; serves as assurance that we have thoroughly validated the identity and details of vendors/services, encompassing names, addresses, contact information, and business names. This verification process relies on the documents or information submitted by the vendors/service providers. The bestowal of the &quot;Famous Business Trusted Tag&quot; is not exclusively contingent on document verification; it may also consider user reviews, ratings, or other relevant criteria as determined by Famous Business.

                </li>
                <li>
                    <strong>
                        Super Seller:</strong>
                    The designation &quot;Famous Business Super Seller&quot; provides assurance that we have meticulously verified the identity and particulars of vendors/services, including names, addresses, contact information, and business names. This verification process is based on the documents or information submitted by the vendors/service providers. The conferment of the &quot;Famous Business Trusted Tag&quot; is not solely contingent on document verification; it may also take into consideration user reviews, ratings, or other pertinent criteria as determined by Famous Business.
                    <p>
                        The title Famous Business Premium Seller ensures that we have scrupulously verified the identity and details of vendors/services, encompassing names, addresses, contact information, and business names. This verification process relies on the documents or information submitted by the vendors/service providers. The awarding of the &quot;Famous Business Trusted Tag&quot; is not exclusively dependent on document verification; it may also consider user reviews, ratings, or other relevant criteria, as determined by Famous Business.



                    </p>

                </li>








                {/* tags */}
                {/* tags */}






























                <li>
                    <strong>Famous Business Trusted Tag:</strong>
                    <p>
                        The <b>&quot;Famous Business Trusted Tag&quot;</b> serves as an indication that the identity and information of the vendors/services, including but not limited to the name, address, contact details, and business name, has been verified on a best-effort basis. This verification is conducted based on the documents or information provided by the vendors/service providers. The allocation of <b>&quot;Famous Business Trusted Tag&quot;</b> is not solely reliant on document verification; it may also take into account user reviews, ratings, or other criteria deemed relevant by Famous Business.
                    </p>
                </li>
            </ol>
        </div>
    )
}

export default Agreement