import Link from 'next/link'
import React from 'react'

function AgreementBuyer() {
    return (
        <div className='dark:text-black'>
            <h1>Defined Terms</h1>

            <ol type='1' className=' space-y-4 '>
                <li>
                    <strong>&quot;Agreement&quot;</strong> This document serves as an electronic record under the amended Information Technology Act, 2000, along with its associated rules and regulations. Generated by a computer system, it does not require any physical or digital signatures. The presentation of this electronic record adheres to Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, mandating the publication of terms for accessing or using services provided by <b>Webzotica Business Famous Software Private Limited</b> through www.famousbusiness.in Portals. This publication aligns with the requirements specified in Section 65B(2) of the Indian Evidence Act, 1872.
                    <p>The Terms of Service delineate the contractual relationship between Vendors (referred to as &quot;Vendor&quot; or &quot;Service Provider,&quot; &quot;You,&quot; or &quot;Your&quot;) and <b>Webzotica Business Famous Software Private Limited </b> (referred to as <Link href=''>Famousbusiness.in</Link>). These terms govern the services offered by <b>Webzotica Business Famous Software Private Limited</b> through its website <a>(www.famousbusiness.in)</a>, APP, or any other medium collectively referred to as &quot;Portals.&quot; Webzotica Business Famous Software Private Limited provides its services exclusively based on the terms outlined in this Terms of Service, along with any subsequent amendments. Webzotica Business Famous Software Private Limited is committed to dispatching the Terms of Service to you via your registered email ID and ensuring its accessibility on Webzotica Business Famous Software Private Limited&apos;s website at <a href='https://famousbusiness.in/about/Terms-Condition/buyer'>https://famousbusiness.in/about/Terms-Condition/buyer</a>.</p>
                    <p>Webzotica Business Famous Software Private Limited, through its Famousbusiness.in Portal, aligns with the Digital India campaign&apos;s mission, aiming to empower millions of Users to Micro, Small & Medium Enterprises (MSMEs) by facilitating their digital transformation. Our commitment involves offering Free Goods and Services Enquiries, supporting the ethos of &apos;Power To Empower.&apos; We leverage technology and innovation to achieve this goal.&quot;</p>
                    <p>The Services, as defined hereinafter, provided by Webzotica Business Famous Software Private Limited through www.famousbusiness.in, are governed by this agreement. Webzotica Business Famous Software Private Limited, a company incorporated under the Companies Act, 1956, has its registered office located at Building 545, Sector-58, Transport Nagar, Ballabgarh, Faridabad-121004, Haryana. Famous Business engages in the business of furnishing information about Vendors, as defined hereinafter, offering various products and services (&apos;Information&apos;) in selected towns and cities in India (&apos;Service&apos;) to end users. Operating as both a B2B and B2C Marketplace, Famous Business primarily provides directory services to its Callers/Users based on their requirements and searches made on www.famousbusiness.in&apos;s portals, as applicable to the vendors.</p>
                </li>

                <li>
                    <strong>The&quot;Service Offered to Users&quot;</strong> refers to a service available to users on the portal, facilitating connections with businesses subscribed to this service. Through this service, a user, potentially a prospective buyer, can contact a listed seller on this portal. The company offering this service commonly refers to it as &apos;click to call,&apos; &apos;click to WhatsApp,&apos; &apos;click to email,&apos; &apos;click to view website,&apos; and &apos;write a message to the seller via messenger,&apos; enabling inquiries from respective users to prospective sellers. </li>

                <li>
                    <strong>&quot;Payment Terms & Conditions&quot;</strong> We do not facilitate any payment sharing between buyers and sellers, nor are we involved in the shipment of goods. Our role is limited to providing digital information to both buyers and sellers. We explicitly disclaim any responsibility for payment-related issues between buyers and sellers. It is the sole responsibility of buyers to exercise caution and diligence in transactions, ensuring they verify the quality of goods or services and the associated warranties before proceeding with any transaction. Any transaction between a buyer and a seller is the buyer&apos;s own responsibility, and we strongly advise conducting thorough assessments before completing any transaction.
                </li>
                <li>
                    <strong>&quot;Digital Personal data Protection&quot;</strong> THE DIGITAL PERSONAL DATA PROTECTION ACT, 2023
                </li>

            </ol>
        </div>
    )
}

export default AgreementBuyer